/**
 * Finite State Machine (FSM) for Enterprise Blackjack Engine
 * Governs strict round state flow and rejects illegal transitions.
 */

export const STATES = {
  BOOT: 'BOOT',
  WAITING_FOR_BET: 'WAITING_FOR_BET',
  BET_PLACED: 'BET_PLACED',
  DEALING_INITIAL_CARDS: 'DEALING_INITIAL_CARDS',
  WAITING_FOR_INSURANCE: 'WAITING_FOR_INSURANCE',
  WAITING_FOR_PLAYER_ACTION: 'WAITING_FOR_PLAYER_ACTION',
  PLAYING_HAND_1: 'PLAYING_HAND_1',
  PLAYING_HAND_2: 'PLAYING_HAND_2',
  PLAYING_HAND_3: 'PLAYING_HAND_3',
  PLAYING_HAND_4: 'PLAYING_HAND_4',
  PLAYER_STAND: 'PLAYER_STAND',
  PLAYER_BUST: 'PLAYER_BUST',
  PLAYER_BLACKJACK: 'PLAYER_BLACKJACK',
  PLAYER_DOUBLE: 'PLAYER_DOUBLE',
  PLAYER_SPLIT: 'PLAYER_SPLIT',
  PLAYER_SURRENDER: 'PLAYER_SURRENDER',
  DEALER_REVEAL: 'DEALER_REVEAL',
  DEALER_PLAY: 'DEALER_PLAY',
  COMPARE_RESULTS: 'COMPARE_RESULTS',
  PAYOUT: 'PAYOUT',
  ROUND_COMPLETE: 'ROUND_COMPLETE',
  RESET_ROUND: 'RESET_ROUND'
};

const TRANSITIONS = {
  [STATES.BOOT]: [STATES.WAITING_FOR_BET],
  [STATES.WAITING_FOR_BET]: [STATES.BET_PLACED],
  [STATES.BET_PLACED]: [STATES.DEALING_INITIAL_CARDS],
  [STATES.DEALING_INITIAL_CARDS]: [
    STATES.WAITING_FOR_INSURANCE,
    STATES.WAITING_FOR_PLAYER_ACTION,
    STATES.PLAYING_HAND_1,
    STATES.PLAYER_BLACKJACK,
    STATES.DEALER_REVEAL,
    STATES.COMPARE_RESULTS,
    STATES.PAYOUT
  ],
  [STATES.WAITING_FOR_INSURANCE]: [
    STATES.WAITING_FOR_PLAYER_ACTION,
    STATES.PLAYING_HAND_1,
    STATES.DEALER_REVEAL,
    STATES.COMPARE_RESULTS,
    STATES.PAYOUT
  ],
  [STATES.WAITING_FOR_PLAYER_ACTION]: [
    STATES.PLAYING_HAND_1,
    STATES.PLAYING_HAND_2,
    STATES.PLAYING_HAND_3,
    STATES.PLAYING_HAND_4,
    STATES.PLAYER_STAND,
    STATES.PLAYER_BUST,
    STATES.PLAYER_DOUBLE,
    STATES.PLAYER_SPLIT,
    STATES.PLAYER_SURRENDER,
    STATES.DEALER_REVEAL,
    STATES.PAYOUT
  ],
  [STATES.PLAYING_HAND_1]: [
    STATES.WAITING_FOR_PLAYER_ACTION,
    STATES.PLAYING_HAND_2,
    STATES.PLAYER_STAND,
    STATES.PLAYER_BUST,
    STATES.PLAYER_DOUBLE,
    STATES.PLAYER_SPLIT,
    STATES.PLAYER_SURRENDER,
    STATES.DEALER_REVEAL,
    STATES.PAYOUT
  ],
  [STATES.PLAYING_HAND_2]: [
    STATES.WAITING_FOR_PLAYER_ACTION,
    STATES.PLAYING_HAND_3,
    STATES.PLAYER_STAND,
    STATES.PLAYER_BUST,
    STATES.PLAYER_DOUBLE,
    STATES.PLAYER_SPLIT,
    STATES.DEALER_REVEAL,
    STATES.PAYOUT
  ],
  [STATES.PLAYING_HAND_3]: [
    STATES.WAITING_FOR_PLAYER_ACTION,
    STATES.PLAYING_HAND_4,
    STATES.PLAYER_STAND,
    STATES.PLAYER_BUST,
    STATES.PLAYER_DOUBLE,
    STATES.PLAYER_SPLIT,
    STATES.DEALER_REVEAL,
    STATES.PAYOUT
  ],
  [STATES.PLAYING_HAND_4]: [
    STATES.WAITING_FOR_PLAYER_ACTION,
    STATES.PLAYER_STAND,
    STATES.PLAYER_BUST,
    STATES.PLAYER_DOUBLE,
    STATES.DEALER_REVEAL,
    STATES.PAYOUT
  ],
  [STATES.PLAYER_STAND]: [STATES.PLAYING_HAND_2, STATES.PLAYING_HAND_3, STATES.PLAYING_HAND_4, STATES.DEALER_REVEAL, STATES.PAYOUT],
  [STATES.PLAYER_BUST]: [STATES.PLAYING_HAND_2, STATES.PLAYING_HAND_3, STATES.PLAYING_HAND_4, STATES.DEALER_REVEAL, STATES.PAYOUT],
  [STATES.PLAYER_BLACKJACK]: [STATES.DEALER_REVEAL, STATES.COMPARE_RESULTS, STATES.PAYOUT],
  [STATES.PLAYER_DOUBLE]: [STATES.PLAYING_HAND_2, STATES.PLAYING_HAND_3, STATES.PLAYING_HAND_4, STATES.DEALER_REVEAL, STATES.PAYOUT],
  [STATES.PLAYER_SPLIT]: [STATES.PLAYING_HAND_1, STATES.WAITING_FOR_PLAYER_ACTION],
  [STATES.PLAYER_SURRENDER]: [STATES.PAYOUT, STATES.ROUND_COMPLETE],
  [STATES.DEALER_REVEAL]: [STATES.DEALER_PLAY, STATES.COMPARE_RESULTS, STATES.PAYOUT],
  [STATES.DEALER_PLAY]: [STATES.COMPARE_RESULTS, STATES.PAYOUT],
  [STATES.COMPARE_RESULTS]: [STATES.PAYOUT],
  [STATES.PAYOUT]: [STATES.ROUND_COMPLETE],
  [STATES.ROUND_COMPLETE]: [STATES.RESET_ROUND, STATES.WAITING_FOR_BET],
  [STATES.RESET_ROUND]: [STATES.WAITING_FOR_BET]
};

export class FiniteStateMachine {
  constructor(initialState = STATES.WAITING_FOR_BET) {
    this.currentState = initialState;
    this.stateHistory = [initialState];
  }

  transitionTo(nextState) {
    if (!STATES[nextState]) {
      throw new Error(`Invalid target state: ${nextState}`);
    }

    const allowed = TRANSITIONS[this.currentState] || [];
    if (!allowed.includes(nextState)) {
      throw new Error(`Illegal state transition: Cannot transition from '${this.currentState}' to '${nextState}'`);
    }

    this.currentState = nextState;
    this.stateHistory.push(nextState);
    return this.currentState;
  }

  getState() {
    return this.currentState;
  }

  isInState(state) {
    return this.currentState === state;
  }

  isTerminalState() {
    return this.currentState === STATES.ROUND_COMPLETE || this.currentState === STATES.PAYOUT;
  }
}
